runtime: nodejs14 # or another supported version

#entrypoint: npm run start
#instance_class: F2

#env_variables:
# BUCKET_NAME: "example-gcs-bucket"


handlers:
- url: /
  static_files: build/index.html
  upload: build/index.html

- url: /(.*)
  static_files: build/\1
  upload: build/(.*)

#handlers:
#- url: /stylesheets
#  static_dir: stylesheets

#- url: /.*
#  static_dir: build
#  secure: always
#  redirect_http_response_code: 301
#  script: auto